/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as StyleRouteImport } from './routes/style'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ViewsIndexRouteImport } from './routes/views.index'
import { Route as ViewsViewIdRouteImport } from './routes/views.$viewId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleRoute = StyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsIndexRoute = ViewsIndexRouteImport.update({
  id: '/views/',
  path: '/views/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsViewIdRoute = ViewsViewIdRouteImport.update({
  id: '/views/$viewId',
  path: '/views/$viewId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keywords': typeof KeywordsRoute
  '/style': typeof StyleRoute
  '/api/inngest': typeof ApiInngestRoute
  '/views/$viewId': typeof ViewsViewIdRoute
  '/views/': typeof ViewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keywords': typeof KeywordsRoute
  '/style': typeof StyleRoute
  '/api/inngest': typeof ApiInngestRoute
  '/views/$viewId': typeof ViewsViewIdRoute
  '/views': typeof ViewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/keywords': typeof KeywordsRoute
  '/style': typeof StyleRoute
  '/api/inngest': typeof ApiInngestRoute
  '/views/$viewId': typeof ViewsViewIdRoute
  '/views/': typeof ViewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/keywords' | '/style' | '/api/inngest' | '/views/$viewId' | '/views/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/keywords' | '/style' | '/api/inngest' | '/views/$viewId' | '/views'
  id:
    | '__root__'
    | '/'
    | '/keywords'
    | '/style'
    | '/api/inngest'
    | '/views/$viewId'
    | '/views/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeywordsRoute: typeof KeywordsRoute
  StyleRoute: typeof StyleRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ViewsViewIdRoute: typeof ViewsViewIdRoute
  ViewsIndexRoute: typeof ViewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style': {
      id: '/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof StyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views/': {
      id: '/views/'
      path: '/views'
      fullPath: '/views/'
      preLoaderRoute: typeof ViewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views/$viewId': {
      id: '/views/$viewId'
      path: '/views/$viewId'
      fullPath: '/views/$viewId'
      preLoaderRoute: typeof ViewsViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeywordsRoute: KeywordsRoute,
  StyleRoute: StyleRoute,
  ApiInngestRoute: ApiInngestRoute,
  ViewsViewIdRoute: ViewsViewIdRoute,
  ViewsIndexRoute: ViewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
